### PR TITLE
Flexbox order

### PR DESCRIPTION
**Pull request by smbdelse**
A suggestion of using another flexbox feature - order combined with media query.

### CODE REVIEW

**Comment by jameskolce** [comment]
Looks good to me! Can you send also the compiled .css file? Then I can merge.

**Comment by jameskolce** [comment]
Also if you can add a test in the [test.html](https://github.com/ConciseCSS/concise.css/blob/master/test.html) file it would be great. Thank you!

**Comment by jameskolce** [comment]
Awesome, thank you! I appreciate your contribution.

**Comment by smbdelse** [comment]
It's pure pleasure to work with Concise. Simply and well organised project.

**Pull request merged**
